---
- name: Install tools to build the project
  hosts: builder
  become: yes

  tasks:
  - name: Ensure git package is present
    apt:
      name: git
      state: present
  
  - name: Ensure JDK package is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

##################################################################################
- name: Build project
  hosts: builder
  become: yes
  
  tasks:
  - name: Cloning a project from a git
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/boxfuse-sample-java-war-hello

  - name: Build a project using the maven
    shell: cd /tmp/boxfuse-sample-java-war-hello && mvn package

##################################################################################
- name: Install and startup web-server Tomcat9
  hosts: prod
  become: yes
  
  tasks:
    - name: Ensure JDK package is present
      apt:
        name: default-jdk
        state: present

    - name: Ensure Tomcat package is present
      apt:
        name: tomcat9
        state: present

    - name: Ensure Tomcat is started
      service:
        name: tomcat9
        state: started

    - name: Copy artifacts from build
      synchronize:
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/hello-1.0.war
      delegate_to: instance-slave-1